# Node data
# The positioning of the baths relative to the home ($H) can be adjusted by changing the x, y and z values below (in cm).
# Negative y is towards the front, negative x is towards the right, and negative z is down
# The specified coord needs to be the position lowered into the bath
# The application assumes that z = 0 is a safe position to move above the bath
#
# The neighbors are the safe paths to move to. The application tells grbl to move to z = 0 before moving between baths.
# Imagine a chess board above the baths, the neighbors are all of the moves that the chess peice (the robot head) can move to from that position. An unlimited number of neighbors can be given, and the application will determine the best path at runtime.
# It is recommended to had as few neighbors as possible, imagine a line of baths. While it would make sense to have the first bath link to the last one as a neighbor, it complicates the run-time prosess. Each bath should only have is neighbors be the one directly next to it. i.e. the first and last baths have 1 neighbor, and all of the intermediate baths have 2 neighbors.
#
# Ordering baths sequentialy in the config is recommended, but not needed. The UI buttons and logic are built from the give x,y coords

[[node]]
name = "MCL_16"
x = -0.1
y = -0.4
z = -10.0
is_rinse = false
neighbors = ["Rinse 1"]

[[node]]
name = "HNO3"
x = -10.2
y = -0.4
z = -10.0
is_rinse = false
neighbors = ["Rinse 2"]

[[node]]
name = "Zn"
x = -20.2
y = -0.5
z = -10.0
is_rinse = false
neighbors = ["Rinse 3"]

[[node]]
name = "HF"
x = -30.3
y = -0.5
z = -10.0
is_rinse = false
neighbors = ["Rinse 4"]

[[node]]
name = "Ni"
x = -40.3
y = -0.5
z = -10.0
is_rinse = false
neighbors = ["Rinse 5"]

[[node]]
name = "Pd"
x = -50.4
y = -0.5
z = -10.0
is_rinse = false
neighbors = ["Rinse 6"]

[[node]]
name = "Au"
x = -60.5
y = -0.5
z = -10.0
is_rinse = false
neighbors = ["Rinse 7"]

[[node]]
name = "Rinse 1"
x = 0.0
y = -13.3
z = -10.0
is_rinse = true
neighbors = ["MCL_16", "Rinse 2"]

[[node]]
name = "Rinse 2"
x = -10.1
y = -13.3
z = -10.0
is_rinse = true
neighbors = ["HNO3", "Rinse 1", "Rinse 3"]

[[node]]
name = "Rinse 3"
x = -20.1
y = -12.4
z = -10.0
is_rinse = true
neighbors = ["Zn", "Rinse 2", "Rinse 4"]

[[node]]
name = "Rinse 4"
x = -30.2
y = -13.4
z = -10.0
is_rinse = true
neighbors = ["HF", "Rinse 3", "Rinse 5"]

[[node]]
name = "Rinse 5"
x = -40.3
y = -13.3
z = -10.0
is_rinse = true
neighbors = ["Ni", "Rinse 4", "Rinse 6"]

[[node]]
name = "Rinse 6"
x = -50.4
y = -13.5
z = -10.0
is_rinse = true
neighbors = ["Pd", "Rinse 5", "Rinse 7"]

[[node]]
name = "Rinse 7"
x = -60.5
y = -13.5
z = -10.0
is_rinse = true
neighbors = ["Au", "Rinse 6"]
