[[node]]
name = 'MCL-16'
x = -1.1
y = -0.3
z = -10.1
hide = false
neighbors = ['Rinse 1']

[[node]]
name = 'HNO₃'
x = -11.2
y = -0.3
z = -10.4
hide = false
neighbors = ['Rinse 2']

[[node]]
name = 'Zn'
x = -21.2
y = -0.3
z = -10.3
hide = false
neighbors = ['Rinse 3']

[[node]]
name = 'HF'
x = -31.3
y = -0.3
z = -10.6
hide = false
neighbors = ['Rinse 4']

[[node]]
name = 'Ni'
x = -41.3
y = -0.3
z = -10.5
hide = false
neighbors = ['Rinse 5']

[[node]]
name = 'Pd'
x = -51.4
y = -0.3
z = -10.4
hide = false
neighbors = ['Rinse 6']

[[node]]
name = 'Au'
x = -61.5
y = -0.3
z = -10.2
hide = false
neighbors = ['Rinse 7']

[[node]]
name = 'HOME'
x = -1.0
y = -14.5
z = -1.0
hide = true
neighbors = ['Rinse 1']

[[node]]
name = 'Rinse 1'
x = -1.0
y = -13.1
z = -10.0
hide = false
neighbors = [
    'MCL-16',
    'Rinse 2',
]

[[node]]
name = 'Rinse 2'
x = -11.1
y = -13.1
z = -10.0
hide = false
neighbors = [
    'HNO₃',
    'Rinse 1',
    'Rinse 3',
]

[[node]]
name = 'Rinse 3'
x = -21.1
y = -13.1
z = -10.0
hide = false
neighbors = [
    'Zn',
    'Rinse 2',
    'Rinse 4',
]

[[node]]
name = 'Rinse 4'
x = -31.2
y = -13.1
z = -10.0
hide = false
neighbors = [
    'HF',
    'Rinse 3',
    'Rinse 5',
]

[[node]]
name = 'Rinse 5'
x = -41.3
y = -13.1
z = -10.0
hide = false
neighbors = [
    'Ni',
    'Rinse 4',
    'Rinse 6',
]

[[node]]
name = 'Rinse 6'
x = -51.4
y = -13.1
z = -10.0
hide = false
neighbors = [
    'Pd',
    'Rinse 5',
    'Rinse 7',
]

[[node]]
name = 'Rinse 7'
x = -61.5
y = -13.1
z = -10.0
hide = false
neighbors = [
    'Au',
    'Rinse 6',
]
